### ISSUE TITLE
Win32Exception on closing window

### ISSUE THREAD

**Issue by dymanoid** [ControlzEx/ControlzEx#13]
We have a WPF app with Fluent.Ribbon that uses this library.

We run this app on a remote machine using Remote Desktop connection.
If the app's main window (with ribbon) is maximized, closing this window causes an exception.
Here is the stack trace:

```
System.ComponentModel.Win32Exception (0x80004005): The parameter is incorrect
   at Standard.NativeMethods.SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, Int32 x, Int32 y, Int32 cx, Int32 cy, SWP uFlags)
   at ControlzEx.Microsoft.Windows.Shell.WindowChromeWorker._HandleMoveForRealSize(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at ControlzEx.Microsoft.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by punker76** [comment]
@dymanoid Which OS is running on the remote machine? Which .Net is installed? Is the OS DWM theme disabled?
^ @batzen any thoughts?

**Comment by dymanoid** [comment]
Remote is Win7 Pro, app target .NET is 4.5.1, installed runtime on remote is 4.5.1. Themes are enabled in the OS and in the Remote Desktop connection settings.

**Comment by batzen** [comment]
Coincidentally i just received the same issue as an internal error report at my company...
Will investigate and fix it as fast as i can.

> #############################################
Report.txt
#############################################
Fehlerdetails:
System.ComponentModel.Win32Exception (0x80004005): Falscher Parameter
   at ControlzEx.Microsoft.Windows.Shell.WindowChromeWorker._HandleMoveForRealSize(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at ControlzEx.Microsoft.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

>#############################################
SystemInformationen.txt
#############################################
Anwendung:
Name:             XXXXX
Version:          16.3.0.0 [118495]
Culture:          de-DE
Admin:            True
Laufzeit:         00:02:55.3821791
Private memory:   200 MB
Working set:      110 MB

>Windows-Benutzer:
Name:             XXXXX

>System:
Datum/Uhrzeit:    16.06.2016 10:32:19
Computername:     XXXXX
Betriebssystem:   Microsoft Windows NT 6.1.7601 Service Pack 1
  64Bit:          True
.NET:             4.0.30319.42000
Auflösung:        1920x1080
Prozessoren:      8
Arbeitsspeicher (Gesamt):
  Physical:       16289 MB
  Virtual:        2047 MB
Arbeitsspeicher (Verfügbar):
  Physical:       13151 MB
  Virtual:        1361 MB

**Comment by batzen** [comment]
@dymanoid Could you try to reproduce the issue using the ControlzEx showcase application and report back?

**Comment by dymanoid** [comment]
Could not reproduce this issue with the showcase app. I will try to debug our app with the ControlzEx.pdb and provide you with additional information.

**Comment by batzen** [comment]
I was able to reproduce the issue on my machine. Working on a fix.
